// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.1
// source: graphs_service/graphs_service.proto

package graphs

import (
	tasks_service "github.com/liriquew/control_system/services_protos/tasks_service"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base Entities
type Graph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	GroupID   int64  `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	CreatedBy int64  `protobuf:"varint,4,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
}

func (x *Graph) Reset() {
	*x = Graph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{0}
}

func (x *Graph) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Graph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Graph) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *Graph) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GraphID           int64   `protobuf:"varint,2,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	TaskID            int64   `protobuf:"varint,3,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	DependencyNodeIDs []int64 `protobuf:"varint,5,rep,packed,name=DependencyNodeIDs,proto3" json:"DependencyNodeIDs,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Node) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

func (x *Node) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *Node) GetDependencyNodeIDs() []int64 {
	if x != nil {
		return x.DependencyNodeIDs
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNodeID int64 `protobuf:"varint,1,opt,name=FromNodeID,proto3" json:"FromNodeID,omitempty"`
	ToNodeID   int64 `protobuf:"varint,2,opt,name=ToNodeID,proto3" json:"ToNodeID,omitempty"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{2}
}

func (x *Dependency) GetFromNodeID() int64 {
	if x != nil {
		return x.FromNodeID
	}
	return 0
}

func (x *Dependency) GetToNodeID() int64 {
	if x != nil {
		return x.ToNodeID
	}
	return 0
}

type GraphWithNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphInfo *Graph  `protobuf:"bytes,1,opt,name=GraphInfo,proto3" json:"GraphInfo,omitempty"`
	Nodes     []*Node `protobuf:"bytes,2,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
}

func (x *GraphWithNodes) Reset() {
	*x = GraphWithNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphWithNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphWithNodes) ProtoMessage() {}

func (x *GraphWithNodes) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphWithNodes.ProtoReflect.Descriptor instead.
func (*GraphWithNodes) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{3}
}

func (x *GraphWithNodes) GetGraphInfo() *Graph {
	if x != nil {
		return x.GraphInfo
	}
	return nil
}

func (x *GraphWithNodes) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIDs []int64 `protobuf:"varint,1,rep,packed,name=NodeIDs,proto3" json:"NodeIDs,omitempty"`
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{4}
}

func (x *Path) GetNodeIDs() []int64 {
	if x != nil {
		return x.NodeIDs
	}
	return nil
}

// Request/Response Messages
type GraphResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{5}
}

func (x *GraphResponse) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

type ListGroupGraphsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Padding int64 `protobuf:"varint,1,opt,name=Padding,proto3" json:"Padding,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *ListGroupGraphsRequest) Reset() {
	*x = ListGroupGraphsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupGraphsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupGraphsRequest) ProtoMessage() {}

func (x *ListGroupGraphsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupGraphsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupGraphsRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListGroupGraphsRequest) GetPadding() int64 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *ListGroupGraphsRequest) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type GraphListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graphs []*GraphWithNodes `protobuf:"bytes,1,rep,name=Graphs,proto3" json:"Graphs,omitempty"`
}

func (x *GraphListResponse) Reset() {
	*x = GraphListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphListResponse) ProtoMessage() {}

func (x *GraphListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphListResponse.ProtoReflect.Descriptor instead.
func (*GraphListResponse) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{7}
}

func (x *GraphListResponse) GetGraphs() []*GraphWithNodes {
	if x != nil {
		return x.Graphs
	}
	return nil
}

type GetGraphRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,2,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetGraphRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

type GetNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	NodeID  int64 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetNodeRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

func (x *GetNodeRequest) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type NodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{10}
}

func (x *NodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"`
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"`
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	NodeID  int64 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveNodeRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

func (x *RemoveNodeRequest) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type GetDependenciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	NodeID  int64 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
}

func (x *GetDependenciesRequest) Reset() {
	*x = GetDependenciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesRequest) ProtoMessage() {}

func (x *GetDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetDependenciesRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

func (x *GetDependenciesRequest) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type NodeWithDependencies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
}

func (x *NodeWithDependencies) Reset() {
	*x = NodeWithDependencies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeWithDependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeWithDependencies) ProtoMessage() {}

func (x *NodeWithDependencies) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeWithDependencies.ProtoReflect.Descriptor instead.
func (*NodeWithDependencies) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{15}
}

func (x *NodeWithDependencies) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DependencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID    int64       `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	Dependency *Dependency `protobuf:"bytes,2,opt,name=Dependency,proto3" json:"Dependency,omitempty"`
}

func (x *DependencyRequest) Reset() {
	*x = DependencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyRequest) ProtoMessage() {}

func (x *DependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyRequest.ProtoReflect.Descriptor instead.
func (*DependencyRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{16}
}

func (x *DependencyRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

func (x *DependencyRequest) GetDependency() *Dependency {
	if x != nil {
		return x.Dependency
	}
	return nil
}

type PredictGraphRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraphID int64 `protobuf:"varint,1,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
}

func (x *PredictGraphRequest) Reset() {
	*x = PredictGraphRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictGraphRequest) ProtoMessage() {}

func (x *PredictGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictGraphRequest.ProtoReflect.Descriptor instead.
func (*PredictGraphRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{17}
}

func (x *PredictGraphRequest) GetGraphID() int64 {
	if x != nil {
		return x.GraphID
	}
	return 0
}

type NodeWithTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node                   *Node               `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
	Task                   *tasks_service.Task `protobuf:"bytes,2,opt,name=Task,proto3" json:"Task,omitempty"`
	AdditionalDependencies []int64             `protobuf:"varint,3,rep,packed,name=AdditionalDependencies,proto3" json:"AdditionalDependencies,omitempty"`
	PredictedTime          float64             `protobuf:"fixed64,4,opt,name=PredictedTime,proto3" json:"PredictedTime,omitempty"`
}

func (x *NodeWithTask) Reset() {
	*x = NodeWithTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeWithTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeWithTask) ProtoMessage() {}

func (x *NodeWithTask) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeWithTask.ProtoReflect.Descriptor instead.
func (*NodeWithTask) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{18}
}

func (x *NodeWithTask) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeWithTask) GetTask() *tasks_service.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *NodeWithTask) GetAdditionalDependencies() []int64 {
	if x != nil {
		return x.AdditionalDependencies
	}
	return nil
}

func (x *NodeWithTask) GetPredictedTime() float64 {
	if x != nil {
		return x.PredictedTime
	}
	return 0
}

type PredictedGraphResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graph           *Graph          `protobuf:"bytes,1,opt,name=Graph,proto3" json:"Graph,omitempty"`
	Nodes           []*NodeWithTask `protobuf:"bytes,2,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	UnpredictedUIDs []int64         `protobuf:"varint,3,rep,packed,name=UnpredictedUIDs,proto3" json:"UnpredictedUIDs,omitempty"`
	Paths           []*Path         `protobuf:"bytes,4,rep,name=Paths,proto3" json:"Paths,omitempty"`
}

func (x *PredictedGraphResponse) Reset() {
	*x = PredictedGraphResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedGraphResponse) ProtoMessage() {}

func (x *PredictedGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedGraphResponse.ProtoReflect.Descriptor instead.
func (*PredictedGraphResponse) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{19}
}

func (x *PredictedGraphResponse) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *PredictedGraphResponse) GetNodes() []*NodeWithTask {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PredictedGraphResponse) GetUnpredictedUIDs() []int64 {
	if x != nil {
		return x.UnpredictedUIDs
	}
	return nil
}

func (x *PredictedGraphResponse) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

type NodeDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID int64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
}

func (x *NodeDoneRequest) Reset() {
	*x = NodeDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDoneRequest) ProtoMessage() {}

func (x *NodeDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDoneRequest.ProtoReflect.Descriptor instead.
func (*NodeDoneRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{20}
}

func (x *NodeDoneRequest) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type TaskInNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID int64 `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
}

func (x *TaskInNodeRequest) Reset() {
	*x = TaskInNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInNodeRequest) ProtoMessage() {}

func (x *TaskInNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInNodeRequest.ProtoReflect.Descriptor instead.
func (*TaskInNodeRequest) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{21}
}

func (x *TaskInNodeRequest) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type TaskInNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID int64 `protobuf:"varint,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
}

func (x *TaskInNodeResponse) Reset() {
	*x = TaskInNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphs_service_graphs_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInNodeResponse) ProtoMessage() {}

func (x *TaskInNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphs_service_graphs_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInNodeResponse.ProtoReflect.Descriptor instead.
func (*TaskInNodeResponse) Descriptor() ([]byte, []int) {
	return file_graphs_service_graphs_service_proto_rawDescGZIP(), []int{22}
}

func (x *TaskInNodeResponse) GetNodeID() int64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

var File_graphs_service_graphs_service_proto protoreflect.FileDescriptor

var file_graphs_service_graphs_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x22, 0x76, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x72,
	0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x6f, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x22, 0x61, 0x0a, 0x0e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x57, 0x69, 0x74,
	0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x47, 0x72, 0x61, 0x70, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x50, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x44, 0x22, 0x43, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x70, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73,
	0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x06, 0x47, 0x72, 0x61, 0x70, 0x68, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x4e, 0x6f, 0x64,
	0x65, 0x22, 0x35, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x22,
	0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x14, 0x4e,
	0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x73, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0a, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x2f, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x44, 0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x4e, 0x6f,
	0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x20, 0x0a, 0x04, 0x4e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x04,
	0x54, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x36, 0x0a,
	0x16, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x16, 0x41,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x16,
	0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x52, 0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x2a, 0x0a, 0x05, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x55, 0x6e, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x55, 0x49, 0x44, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x0f, 0x55, 0x6e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x55, 0x49, 0x44,
	0x73, 0x12, 0x22, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x68, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x05,
	0x50, 0x61, 0x74, 0x68, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x22, 0x2b, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x2c, 0x0a,
	0x12, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x32, 0xbe, 0x06, 0x0a, 0x06,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x73, 0x12, 0x41, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x72, 0x61, 0x70, 0x68, 0x73, 0x12, 0x1e, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x57, 0x69, 0x74, 0x68, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a,
	0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4f,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12,
	0x42, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x19, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73,
	0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x0c, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73,
	0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x72, 0x69, 0x71,
	0x75, 0x65, 0x77, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x3b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graphs_service_graphs_service_proto_rawDescOnce sync.Once
	file_graphs_service_graphs_service_proto_rawDescData = file_graphs_service_graphs_service_proto_rawDesc
)

func file_graphs_service_graphs_service_proto_rawDescGZIP() []byte {
	file_graphs_service_graphs_service_proto_rawDescOnce.Do(func() {
		file_graphs_service_graphs_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_graphs_service_graphs_service_proto_rawDescData)
	})
	return file_graphs_service_graphs_service_proto_rawDescData
}

var file_graphs_service_graphs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_graphs_service_graphs_service_proto_goTypes = []interface{}{
	(*Graph)(nil),                  // 0: graphs.Graph
	(*Node)(nil),                   // 1: graphs.Node
	(*Dependency)(nil),             // 2: graphs.Dependency
	(*GraphWithNodes)(nil),         // 3: graphs.GraphWithNodes
	(*Path)(nil),                   // 4: graphs.Path
	(*GraphResponse)(nil),          // 5: graphs.GraphResponse
	(*ListGroupGraphsRequest)(nil), // 6: graphs.ListGroupGraphsRequest
	(*GraphListResponse)(nil),      // 7: graphs.GraphListResponse
	(*GetGraphRequest)(nil),        // 8: graphs.GetGraphRequest
	(*GetNodeRequest)(nil),         // 9: graphs.GetNodeRequest
	(*NodeResponse)(nil),           // 10: graphs.NodeResponse
	(*CreateNodeRequest)(nil),      // 11: graphs.CreateNodeRequest
	(*UpdateNodeRequest)(nil),      // 12: graphs.UpdateNodeRequest
	(*RemoveNodeRequest)(nil),      // 13: graphs.RemoveNodeRequest
	(*GetDependenciesRequest)(nil), // 14: graphs.GetDependenciesRequest
	(*NodeWithDependencies)(nil),   // 15: graphs.NodeWithDependencies
	(*DependencyRequest)(nil),      // 16: graphs.DependencyRequest
	(*PredictGraphRequest)(nil),    // 17: graphs.PredictGraphRequest
	(*NodeWithTask)(nil),           // 18: graphs.NodeWithTask
	(*PredictedGraphResponse)(nil), // 19: graphs.PredictedGraphResponse
	(*NodeDoneRequest)(nil),        // 20: graphs.NodeDoneRequest
	(*TaskInNodeRequest)(nil),      // 21: graphs.TaskInNodeRequest
	(*TaskInNodeResponse)(nil),     // 22: graphs.TaskInNodeResponse
	(*tasks_service.Task)(nil),     // 23: tasks.Task
	(*emptypb.Empty)(nil),          // 24: google.protobuf.Empty
}
var file_graphs_service_graphs_service_proto_depIdxs = []int32{
	0,  // 0: graphs.GraphWithNodes.GraphInfo:type_name -> graphs.Graph
	1,  // 1: graphs.GraphWithNodes.Nodes:type_name -> graphs.Node
	3,  // 2: graphs.GraphListResponse.Graphs:type_name -> graphs.GraphWithNodes
	1,  // 3: graphs.NodeResponse.Node:type_name -> graphs.Node
	1,  // 4: graphs.CreateNodeRequest.Node:type_name -> graphs.Node
	1,  // 5: graphs.UpdateNodeRequest.Node:type_name -> graphs.Node
	1,  // 6: graphs.NodeWithDependencies.Node:type_name -> graphs.Node
	2,  // 7: graphs.DependencyRequest.Dependency:type_name -> graphs.Dependency
	1,  // 8: graphs.NodeWithTask.Node:type_name -> graphs.Node
	23, // 9: graphs.NodeWithTask.Task:type_name -> tasks.Task
	0,  // 10: graphs.PredictedGraphResponse.Graph:type_name -> graphs.Graph
	18, // 11: graphs.PredictedGraphResponse.Nodes:type_name -> graphs.NodeWithTask
	4,  // 12: graphs.PredictedGraphResponse.Paths:type_name -> graphs.Path
	3,  // 13: graphs.Graphs.CreateGroupGraph:input_type -> graphs.GraphWithNodes
	6,  // 14: graphs.Graphs.ListGroupGraphs:input_type -> graphs.ListGroupGraphsRequest
	8,  // 15: graphs.Graphs.GetGraph:input_type -> graphs.GetGraphRequest
	9,  // 16: graphs.Graphs.GetNode:input_type -> graphs.GetNodeRequest
	11, // 17: graphs.Graphs.CreateNode:input_type -> graphs.CreateNodeRequest
	12, // 18: graphs.Graphs.UpdateNode:input_type -> graphs.UpdateNodeRequest
	13, // 19: graphs.Graphs.RemoveNode:input_type -> graphs.RemoveNodeRequest
	14, // 20: graphs.Graphs.GetDependencies:input_type -> graphs.GetDependenciesRequest
	16, // 21: graphs.Graphs.AddDependency:input_type -> graphs.DependencyRequest
	16, // 22: graphs.Graphs.RemoveDependency:input_type -> graphs.DependencyRequest
	17, // 23: graphs.Graphs.PredictGraph:input_type -> graphs.PredictGraphRequest
	21, // 24: graphs.Graphs.TaskInNode:input_type -> graphs.TaskInNodeRequest
	5,  // 25: graphs.Graphs.CreateGroupGraph:output_type -> graphs.GraphResponse
	7,  // 26: graphs.Graphs.ListGroupGraphs:output_type -> graphs.GraphListResponse
	3,  // 27: graphs.Graphs.GetGraph:output_type -> graphs.GraphWithNodes
	10, // 28: graphs.Graphs.GetNode:output_type -> graphs.NodeResponse
	10, // 29: graphs.Graphs.CreateNode:output_type -> graphs.NodeResponse
	24, // 30: graphs.Graphs.UpdateNode:output_type -> google.protobuf.Empty
	24, // 31: graphs.Graphs.RemoveNode:output_type -> google.protobuf.Empty
	15, // 32: graphs.Graphs.GetDependencies:output_type -> graphs.NodeWithDependencies
	24, // 33: graphs.Graphs.AddDependency:output_type -> google.protobuf.Empty
	24, // 34: graphs.Graphs.RemoveDependency:output_type -> google.protobuf.Empty
	19, // 35: graphs.Graphs.PredictGraph:output_type -> graphs.PredictedGraphResponse
	22, // 36: graphs.Graphs.TaskInNode:output_type -> graphs.TaskInNodeResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_graphs_service_graphs_service_proto_init() }
func file_graphs_service_graphs_service_proto_init() {
	if File_graphs_service_graphs_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graphs_service_graphs_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphWithNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupGraphsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGraphRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDependenciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeWithDependencies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictGraphRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeWithTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedGraphResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphs_service_graphs_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graphs_service_graphs_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graphs_service_graphs_service_proto_goTypes,
		DependencyIndexes: file_graphs_service_graphs_service_proto_depIdxs,
		MessageInfos:      file_graphs_service_graphs_service_proto_msgTypes,
	}.Build()
	File_graphs_service_graphs_service_proto = out.File
	file_graphs_service_graphs_service_proto_rawDesc = nil
	file_graphs_service_graphs_service_proto_goTypes = nil
	file_graphs_service_graphs_service_proto_depIdxs = nil
}
