services:
  postgres:
    container_name: psql_for_system
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: control_system_db
      PGDATA: /data/postgres

    ports:
      - "5432:5432"
    
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_for_system
    image: dpage/pgadmin4:latest

    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: somemail@example.com
      PGADMIN_DEFAULT_PASSWORD: passw0rd
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"

    restart: unless-stopped

volumes:
  pgadmin:
