version: "3"

tasks:
  make_migration_auth:
    aliases:
      - migrate_auth
    cmds:
      - migrate -path auth_service/migrations -database "postgresql://postgres:passw0rd@localhost:5432/control_system_auth?sslmode=disable" -verbose up

  make_migration_tasks:
    aliases:
      - migrate_tasks
    cmds:
      - migrate -path tasks_service/migrations -database "postgresql://postgres:passw0rd@localhost:5432/control_system_tasks?sslmode=disable" -verbose up


  make_migration_groups:
    aliases:
      - migrate_groups
    cmds:
      - migrate -path groups_service/migrations -database "postgresql://postgres:passw0rd@localhost:5432/control_system_groups?sslmode=disable" -verbose up

  make_migration_graphs:
    aliases:
      - migrate_graphs
    cmds:
      - migrate -path graphs_service/migrations -database "postgresql://postgres:passw0rd@localhost:5432/control_system_graphs?sslmode=disable" -verbose up

  make_migration_predictions:
    aliases:
      - migrate_predictions
    cmds:
      - migrate -path predictions_service/migrations -database "postgresql://postgres:passw0rd@localhost:5432/control_system_predictions?sslmode=disable" -verbose up

  migrate_all: 
    cmds:
      - go-task migrate_auth && go-task migrate_tasks && go-task migrate_groups && go-task migrate_graphs && go-task migrate_predictions

  gen_golang_proto_auth_srv:
    aliases:
      - gen_go_auth
    cmds:
      - >
        protoc -I proto proto/auth_service/*.proto --go_out=./service_protos --go_opt=paths=source_relative 
        --go-grpc_out=./service_protos --go-grpc_opt=paths=source_relative 

  gen_python_proto_predict_srv:
    aliases:
      - gen_py_prd
    cmds:
      - >
        predictions_service/venv/bin/python -m grpc_tools.protoc -I proto proto/predictions_service/*.proto 
        --python_out=./predictions_service --grpc_python_out=./predictions_service
        --pyi_out=./predictions_service --proto_path=./predictions_service

  gen_golang_proto_predict_srv:
    aliases:
      - gen_go_prd
    cmds:
      - >
        protoc -I proto proto/predictions_service/*.proto --go_out=./service_protos --go_opt=paths=source_relative 
        --go-grpc_out=./service_protos --go-grpc_opt=paths=source_relative

  gen_golang_proto_tasks_srv:
    aliases:
      - gen_go_tsk
    cmds:
      - >
        protoc -I proto proto/tasks_service/*.proto --go_out=./service_protos --go_opt=paths=source_relative 
        --go-grpc_out=./service_protos --go-grpc_opt=paths=source_relative

  gen_golang_proto_groups_srv:
    aliases:
      - gen_go_grp
    cmds:
      - >
        protoc -I proto proto/groups_service/*.proto --go_out=./service_protos --go_opt=paths=source_relative 
        --go-grpc_out=./service_protos --go-grpc_opt=paths=source_relative

  gen_golang_proto_graphs_srv:
    aliases:
      - gen_go_grphs
    cmds:
      - >
        protoc -I proto proto/graphs_service/*.proto proto/tasks_service/*.proto --go_out=./service_protos --go_opt=paths=source_relative 
        --go-grpc_out=./service_protos --go-grpc_opt=paths=source_relative

  gen_all: 
    cmds:
      - go-task gen_go_auth && go-task gen_go_tsk && go-task gen_go_grp && go-task gen_go_grphs && go-task gen_go_prd && go-task gen_py_prd