// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.1
// source: tasks_service/tasks_service.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedBy   int64                  `protobuf:"varint,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	AssignedTo  int64                  `protobuf:"varint,3,opt,name=AssignedTo,proto3" json:"AssignedTo,omitempty"`
	GroupID     int64                  `protobuf:"varint,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Title       string                 `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	PlannedTime float64                `protobuf:"fixed64,7,opt,name=PlannedTime,proto3" json:"PlannedTime,omitempty"`
	Tags        []int32                `protobuf:"varint,8,rep,packed,name=Tags,proto3" json:"Tags,omitempty"`
	ActualTime  float64                `protobuf:"fixed64,9,opt,name=ActualTime,proto3" json:"ActualTime,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Task) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Task) GetAssignedTo() int64 {
	if x != nil {
		return x.AssignedTo
	}
	return 0
}

func (x *Task) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPlannedTime() float64 {
	if x != nil {
		return x.PlannedTime
	}
	return 0
}

func (x *Task) GetTags() []int32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetActualTime() float64 {
	if x != nil {
		return x.ActualTime
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TaskList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *TaskID) Reset() {
	*x = TaskID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskID) ProtoMessage() {}

func (x *TaskID) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskID.ProtoReflect.Descriptor instead.
func (*TaskID) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{2}
}

func (x *TaskID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskID) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type GroupID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GroupID) Reset() {
	*x = GroupID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupID) ProtoMessage() {}

func (x *GroupID) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupID.ProtoReflect.Descriptor instead.
func (*GroupID) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{3}
}

func (x *GroupID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type TaskExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID  int64 `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *TaskExistsRequest) Reset() {
	*x = TaskExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExistsRequest) ProtoMessage() {}

func (x *TaskExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExistsRequest.ProtoReflect.Descriptor instead.
func (*TaskExistsRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{4}
}

func (x *TaskExistsRequest) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *TaskExistsRequest) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type TaskListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *TaskListRequest) Reset() {
	*x = TaskListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListRequest) ProtoMessage() {}

func (x *TaskListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListRequest.ProtoReflect.Descriptor instead.
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{5}
}

func (x *TaskListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PredictedTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task          *Task   `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	PredictedTime float64 `protobuf:"fixed64,2,opt,name=PredictedTime,proto3" json:"PredictedTime,omitempty"`
	Predicted     bool    `protobuf:"varint,3,opt,name=Predicted,proto3" json:"Predicted,omitempty"`
}

func (x *PredictedTask) Reset() {
	*x = PredictedTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedTask) ProtoMessage() {}

func (x *PredictedTask) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedTask.ProtoReflect.Descriptor instead.
func (*PredictedTask) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{6}
}

func (x *PredictedTask) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *PredictedTask) GetPredictedTime() float64 {
	if x != nil {
		return x.PredictedTime
	}
	return 0
}

func (x *PredictedTask) GetPredicted() bool {
	if x != nil {
		return x.Predicted
	}
	return false
}

type PredictedTaskList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks           []*PredictedTask `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	UnpredictedUIDs []int64          `protobuf:"varint,2,rep,packed,name=UnpredictedUIDs,proto3" json:"UnpredictedUIDs,omitempty"`
}

func (x *PredictedTaskList) Reset() {
	*x = PredictedTaskList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedTaskList) ProtoMessage() {}

func (x *PredictedTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedTaskList.ProtoReflect.Descriptor instead.
func (*PredictedTaskList) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{7}
}

func (x *PredictedTaskList) GetTasks() []*PredictedTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *PredictedTaskList) GetUnpredictedUIDs() []int64 {
	if x != nil {
		return x.UnpredictedUIDs
	}
	return nil
}

type TasksIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []int64 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *TasksIDs) Reset() {
	*x = TasksIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksIDs) ProtoMessage() {}

func (x *TasksIDs) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksIDs.ProtoReflect.Descriptor instead.
func (*TasksIDs) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{8}
}

func (x *TasksIDs) GetIDs() []int64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type TaskTimes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlannedTime float64 `protobuf:"fixed64,2,opt,name=PlannedTime,proto3" json:"PlannedTime,omitempty"`
	ActualTime  float64 `protobuf:"fixed64,3,opt,name=ActualTime,proto3" json:"ActualTime,omitempty"`
}

func (x *TaskTimes) Reset() {
	*x = TaskTimes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTimes) ProtoMessage() {}

func (x *TaskTimes) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTimes.ProtoReflect.Descriptor instead.
func (*TaskTimes) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{9}
}

func (x *TaskTimes) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskTimes) GetPlannedTime() float64 {
	if x != nil {
		return x.PlannedTime
	}
	return 0
}

func (x *TaskTimes) GetActualTime() float64 {
	if x != nil {
		return x.ActualTime
	}
	return 0
}

type TasksTimes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times []*TaskTimes `protobuf:"bytes,1,rep,name=Times,proto3" json:"Times,omitempty"`
}

func (x *TasksTimes) Reset() {
	*x = TasksTimes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksTimes) ProtoMessage() {}

func (x *TasksTimes) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksTimes.ProtoReflect.Descriptor instead.
func (*TasksTimes) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{10}
}

func (x *TasksTimes) GetTimes() []*TaskTimes {
	if x != nil {
		return x.Times
	}
	return nil
}

type TaskDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID int64   `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	Time   float64 `protobuf:"fixed64,2,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *TaskDoneRequest) Reset() {
	*x = TaskDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_service_tasks_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDoneRequest) ProtoMessage() {}

func (x *TaskDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_service_tasks_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDoneRequest.ProtoReflect.Descriptor instead.
func (*TaskDoneRequest) Descriptor() ([]byte, []int) {
	return file_tasks_service_tasks_service_proto_rawDescGZIP(), []int{11}
}

func (x *TaskDoneRequest) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *TaskDoneRequest) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_tasks_service_tasks_service_proto protoreflect.FileDescriptor

var file_tasks_service_tasks_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x02, 0x0a, 0x04, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x75, 0x61,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x2d, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x22, 0x32, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x22, 0x19, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x45, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x74, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1f, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x22, 0x69, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x55, 0x6e, 0x70, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x55, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0f, 0x55, 0x6e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x55, 0x49,
	0x44, 0x73, 0x22, 0x1c, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x49, 0x44, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x49, 0x44, 0x73,
	0x22, 0x5d, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x34, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x26, 0x0a,
	0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x05,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x32, 0x9a, 0x04, 0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x28,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0b, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x0d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x44, 0x1a, 0x0b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x36, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x32, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0d,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x1a, 0x14, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x3e, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x12, 0x0e, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x0f, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x49, 0x44, 0x73, 0x1a, 0x18, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x6f, 0x6e,
	0x65, 0x12, 0x16, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x6f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x69, 0x72, 0x69, 0x71, 0x75, 0x65, 0x77, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tasks_service_tasks_service_proto_rawDescOnce sync.Once
	file_tasks_service_tasks_service_proto_rawDescData = file_tasks_service_tasks_service_proto_rawDesc
)

func file_tasks_service_tasks_service_proto_rawDescGZIP() []byte {
	file_tasks_service_tasks_service_proto_rawDescOnce.Do(func() {
		file_tasks_service_tasks_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tasks_service_tasks_service_proto_rawDescData)
	})
	return file_tasks_service_tasks_service_proto_rawDescData
}

var file_tasks_service_tasks_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tasks_service_tasks_service_proto_goTypes = []interface{}{
	(*Task)(nil),                  // 0: tasks.Task
	(*TaskList)(nil),              // 1: tasks.TaskList
	(*TaskID)(nil),                // 2: tasks.TaskID
	(*GroupID)(nil),               // 3: tasks.GroupID
	(*TaskExistsRequest)(nil),     // 4: tasks.TaskExistsRequest
	(*TaskListRequest)(nil),       // 5: tasks.TaskListRequest
	(*PredictedTask)(nil),         // 6: tasks.PredictedTask
	(*PredictedTaskList)(nil),     // 7: tasks.PredictedTaskList
	(*TasksIDs)(nil),              // 8: tasks.TasksIDs
	(*TaskTimes)(nil),             // 9: tasks.TaskTimes
	(*TasksTimes)(nil),            // 10: tasks.TasksTimes
	(*TaskDoneRequest)(nil),       // 11: tasks.TaskDoneRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_tasks_service_tasks_service_proto_depIdxs = []int32{
	12, // 0: tasks.Task.CreatedAt:type_name -> google.protobuf.Timestamp
	0,  // 1: tasks.TaskList.Tasks:type_name -> tasks.Task
	0,  // 2: tasks.PredictedTask.Task:type_name -> tasks.Task
	6,  // 3: tasks.PredictedTaskList.Tasks:type_name -> tasks.PredictedTask
	9,  // 4: tasks.TasksTimes.Times:type_name -> tasks.TaskTimes
	0,  // 5: tasks.Tasks.CreateTask:input_type -> tasks.Task
	2,  // 6: tasks.Tasks.GetTask:input_type -> tasks.TaskID
	5,  // 7: tasks.Tasks.GetTaskList:input_type -> tasks.TaskListRequest
	0,  // 8: tasks.Tasks.UpdateTask:input_type -> tasks.Task
	2,  // 9: tasks.Tasks.DeleteTask:input_type -> tasks.TaskID
	2,  // 10: tasks.Tasks.PredictTask:input_type -> tasks.TaskID
	4,  // 11: tasks.Tasks.TaskExists:input_type -> tasks.TaskExistsRequest
	3,  // 12: tasks.Tasks.GetGroupTasks:input_type -> tasks.GroupID
	8,  // 13: tasks.Tasks.GetPredictedTasks:input_type -> tasks.TasksIDs
	11, // 14: tasks.Tasks.TaskDone:input_type -> tasks.TaskDoneRequest
	2,  // 15: tasks.Tasks.CreateTask:output_type -> tasks.TaskID
	0,  // 16: tasks.Tasks.GetTask:output_type -> tasks.Task
	1,  // 17: tasks.Tasks.GetTaskList:output_type -> tasks.TaskList
	13, // 18: tasks.Tasks.UpdateTask:output_type -> google.protobuf.Empty
	13, // 19: tasks.Tasks.DeleteTask:output_type -> google.protobuf.Empty
	6,  // 20: tasks.Tasks.PredictTask:output_type -> tasks.PredictedTask
	13, // 21: tasks.Tasks.TaskExists:output_type -> google.protobuf.Empty
	1,  // 22: tasks.Tasks.GetGroupTasks:output_type -> tasks.TaskList
	7,  // 23: tasks.Tasks.GetPredictedTasks:output_type -> tasks.PredictedTaskList
	13, // 24: tasks.Tasks.TaskDone:output_type -> google.protobuf.Empty
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tasks_service_tasks_service_proto_init() }
func file_tasks_service_tasks_service_proto_init() {
	if File_tasks_service_tasks_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tasks_service_tasks_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedTaskList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTimes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksTimes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_service_tasks_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tasks_service_tasks_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_service_tasks_service_proto_goTypes,
		DependencyIndexes: file_tasks_service_tasks_service_proto_depIdxs,
		MessageInfos:      file_tasks_service_tasks_service_proto_msgTypes,
	}.Build()
	File_tasks_service_tasks_service_proto = out.File
	file_tasks_service_tasks_service_proto_rawDesc = nil
	file_tasks_service_tasks_service_proto_goTypes = nil
	file_tasks_service_tasks_service_proto_depIdxs = nil
}
