service_config:
  port: 50053
auth_service:
  host: localhost
  port: 50051
  timeout: 1s
  retries: 1
postgres:
  username: postgres
  password: passw0rd
  host: localhost
  port: 5432
  db_name: control_system_groups