service_config:
  port: 50054
predictions_service:
  host: predictions-service
  port: 50052
  timeout: 1s
  retries: 1
graphs_service:
  host: graphs-service
  port: 50055
  timeout: 1s
  retries: 1
postgres:
  username: postgres
  password: passw0rd
  host: postgres
  port: 5432
  db_name: control_system_tasks
kafka:
  bootstrap_servers: "kafka:9092" # or kafka-like (btw)
  topic: "predictions"
  topic_delete: "predictions_delete"