api_gateway:
  port: 8080
  host: 127.0.0.1
auth_service:
  host: localhost
  port: 50051
  timeout: 1s
  retries: 1
predictions_service:
  host: localhost
  port: 50052
  timeout: 1s
  retries: 1
groups_service:
  host: localhost
  port: 50053
  timeout: 1s
  retries: 1
tasks_service:
  host: localhost
  port: 50054
  timeout: 1s
  retries: 1
graphs_service:
  host: localhost
  port: 50055
  timeout: 1s
  retries: 1