postgres:
  username: postgres
  password: passw0rd
  host: localhost
  port: 5432
  db_name: control_system
predictions_service:
  host: localhost
  port: 4041
api_service:
  host: 127.0.0.1
  port: 8080